name: deepneural-pynet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipython=8.4.0
#  - cupy=11.0.0
  - numpy=1.23.1
  - pandas=1.4.3
  - matplotlib=3.5.3
  - jupyterlab=3.4.5